### ISSUE TITLE
ALSA support

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/capsule#40]
Soooooooooooooooo

Some folks don't use pulseaudio on their system, which is great!

ALSA doesn't have out-of-the-box monitor sinks (snd-aloop exists, but it requires configuration) ... which is less great!

I don't feel like reimplementing libasound2.so, nor do I feel like hooking it and potentially destroying audio performance with my naughty naughty code.

Luckily there *is* a piece of software that already can sit on top of ALSA/OSS and handle monitoring (/loopback) and resampling for us and its name is... pulseaudio!

Contrary to popular belief, pulseaudio isn't that big when you build it without all the ~nonsense~ options, look at this beautiful beautiful ldd output:

```
[amos@testbed bin]$ ldd pulseaudio
        linux-vdso.so.1 (0x00007ffe0f154000)
        libpulsecore-10.0.so => /home/amos/pa-prefix/lib/pulseaudio/libpulsecore-10.0.so (0x00007f90ab9dc000)
        libpulsecommon-10.0.so => /home/amos/pa-prefix/lib/pulseaudio/libpulsecommon-10.0.so (0x00007f90ab766000)
        libpulse.so.0 => /home/amos/pa-prefix/lib/libpulse.so.0 (0x00007f90ab517000)
        libltdl.so.7 => /usr/lib/libltdl.so.7 (0x00007f90ab30d000)
        libgdbm.so.4 => /usr/lib/libgdbm.so.4 (0x00007f90ab101000)
        libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f90aaefd000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f90aacdf000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f90aaad7000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f90aa8d3000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f90aa5c0000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f90aa21c000)
        libsndfile.so.1 => /home/amos/pa-prefix/lib/libsndfile.so.1 (0x00007f90a9faf000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f90abc76000)
```

That's not half bad. To give you an idea of the sizes:

```
2.3M    /home/amos/pa-prefix/lib/pulseaudio/libpulsecore-10.0.so
1.7M    /home/amos/pa-prefix/lib/pulseaudio/libpulsecommon-10.0.so
1.2M    /home/amos/pa-prefix/lib/libpulse.so.0.20.1
40K     /usr/lib/libltdl.so.7.3.1
48K     /usr/lib/libgdbm.so.4.0.0
20K     /usr/lib/libcap.so.2.25
144K    /usr/lib/libpthread-2.25.so
32K     /usr/lib/librt-2.25.so
16K     /usr/lib/libdl-2.25.so
1.1M    /usr/lib/libm-2.25.so
1.9M    /usr/lib/libc-2.25.so
2.0M    /home/amos/pa-prefix/lib/libsndfile.so.1.0.27
11M     total
```

some of these we won't ship cause they're builtins (like libm, libc), and some of these are not stripped yet, and .so files usually compress very well, so the download size will be quite small indeed.

That's a custom compile of pulseaudio and libsndfile, of course, since they both tend to want to link against everything.

  * Here are the [custom compile instructions](https://gist.github.com/fasterthanlime/66120094af12fab3d4019337dd7eb348)

pulseaudio can be started in the foreground (which means it can be started by capsulerun, if it doesn't detect an already running pulse server), and we can give it a non-standard socket path so other apps don't mistakenly connect to it, like so:

```
PULSE_RUNTIME_PATH=/tmp/private-pulse $PREFIX/bin/pulseaudio -vvv
```

And pulse consumers can be run with:

```
PULSE_SERVER=unix:/tmp/private-pulse/native ./game.x86_64
```

That's it!

(ps: the caveat is that the pulseaudio server locks exclusive access to the ALSA device so other ALSA apps won't be able to access audio while the game is playing audio.

obviously this will come with a flag to disable it in case it ruins everything.)

**Comment by fasterthanlime** [comment]
Pre-empting feedback: one common gripe with pulseaudio is that it introduces lag/stutter: various wikis agree that it's usually do to the resampling algorithm used (it defaults to a slow/fancy one) - the custom build defaults to a fast one (it doesn't even rely on speex).

If anyone:

  * Is not using pulseaudio because of lag/stutter
  * Is willing to help me test that the custom build does not introduce that

I'll gladly post test instructions so we can validate the approach.

**Comment by DrMcCoy** [comment]
> the caveat is that the pulseaudio server locks exclusive access to the ALSA device so other ALSA apps won't be able to access audio while the game is playing audio

It claims volume control too. Apart from the lag and stutter, that's really the major issue I have with pulse: it grabs control away from me.

I tend to play with the game on one monitor, IRC on the other. I do occasionally pause the game and switch to my second monitor to follow a link to, say, youtube from IRC. Losing that would be annoying.

I feel the same for the infuriating "mute on focus loss" or even "minimize on focus loss" many games do. Hell, my volume control hotkeys are often interpreted as "focus loss".

On the other hand, if this is just done for capsule, user-configurable and not forced on people (because, for example, the itch.io app always starts it), I'm for one am okay with it. I myself don't really see myself using capsule anyway, so I'm not even the target audience.

**Comment by fasterthanlime** [comment]
> On the other hand, if this is just done for capsule, user-configurable and not forced on people (because, for example, the itch.io app always starts it)

So capsule will be opt-in for a while (while it's in beta) but the goal is to have it stable enough to the default in the itch.io app (so it'll become opt-out at some point). At this point there should be settings to either disable `audio hjiacking` (on linux) or capsule altogether, both globally and per-game.

> I don't feel like reimplementing libasound2.so

I'm going to give this solution half a day of research, to see if it's actually as hard as I thought. Hooking is my favorite way of doing things because it's limited to the game being launched (so for example we wouldn't have the problem of non-game audio cluttering the recording), but only when I know when I'm doing. I have a vague idea how CoreAudio works, a pretty good idea how Pulse does, but only a very thin one of how ALSA works (and the API surface seems large) - but I'm willing to try & see what calls a typical game makes to libasound2.so

**Comment by fasterthanlime** [comment]
The half-day of research has [proved fruitful](https://twitter.com/fasterthanlime/status/847138617948618756) (/cc @DrMcCoy).

In summary:

  * A simple tool like aplay uses a whopping 31 ALSA functions - but only a few of them matter
  * There's ~3 methods to send audio to ALSA
    * the `snd_pcm_write*` family of functions (passing buffers directly) - that's what aplay uses
    * the `snd_async_add_pcm_handler` function (similar to what CoreAudio does) - yet to see it in the wild
    * the `snd_mmap_{begin,commit}` couple of functions: used by OpenAL-soft (Love2D, FNA) and Overland (Unity/WWise, might be using FMOD(EX) under the hood?)

I've started hooking ALSA functions and was able to capture audio from real-world games.

Actually finishing this requires a slight adjustment in capsule's architecture: it's the (belated) arrival of `IPCAudioReceiver` - when we get access to actual audio frames in the game process rather than the encoder process.

I'm hoping the synchronization costs won't cause xruns, I guess we'll find out soon enough!

Note that `IPCAudioReceiver` will also be useful on macOS if I successfully manage to hook CoreAudio, thus alleviating the need for Soundflower!

**Comment by fasterthanlime** [comment]
Quick update:

  * The capsule IPC protocol has been updated to reflect audio intercept capabilities
  * capsulerun is now aware whether audio interception is available, and prefers that, otherwise it falls back to trying PulseAudio loopback/monitor capture
  * ALSA hooks now query the pcm HW params such as format, rate, channels, and access: so far only F32LE is supported, and MMAP interleaved.
  * AudioInterceptReceiver is well on its way, I've got a working prototype that records a 4s buffer (it doesn't quite behave like a ring buffer yet)

Here's a [tweet as proof](https://twitter.com/fasterthanlime/status/847206605217284096) :)

**Comment by fasterthanlime** [comment]
I finished up a naive ring buffer implementation, and it works! Needs cleanups / more tests, but it'll do for now. Closing this as I've merged the alsa branch into master.
