### ISSUE TITLE
macos: only fall back to APPLE on 2.1 contexts (or just detect glGenVertexArrays errors)

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/capsule#49]

**Comment by KevinTKnight** [comment]
I'm an OpenGL amature, but on 4.1 I had to update the shaders in gl_shaders.h as well to enable the Overlay Shader to compile properly. (attribute to in, etc.)

**Comment by KevinTKnight** [comment]
I'm an OpenGL amateur, but on 4.1 I had to update the shaders in gl_shaders.h as well to enable the Overlay Shader to compile properly. (attribute to in, etc.)

**Comment by fasterthanlime** [comment]
@KevinTKnight this is a slightly different error condition, I've just opened #52 to cover it.

**Comment by fasterthanlime** [comment]
Woop, fixed in #55
