### ISSUE TITLE
libcapsule/libcapsule.so: undefined symbol: XOpenDisplay

### ISSUE THREAD

**Issue by fractilegames** [itchio/capsule#7]
I built FFMpeg 3.2.4 and Capsule on Xubuntu 16.04 (x86_64). When trying to run it, I get this:

```
./capsulerun/capsulerun libcapsule /home/mikko/fractilegames/build/astronautics-0.0.8-linux64/astronautics
thanks for flying capsule on GNU/Linux
pid 14904 given to child /home/mikko/fractilegames/build/astronautics-0.0.8-linux64/astronautics
[capsule] Initializing (pid 14904)...
[capsule] LD_LIBRARY_PATH: (null)
[capsule] LD_PRELOAD: libcapsule/libcapsule.so
[capsule] CAPSULE_PIPE_PATH: /tmp/capsule.rawvideo
/home/mikko/fractilegames/build/astronautics-0.0.8-linux64/astronautics: symbol lookup error: libcapsule/libcapsule.so: undefined symbol: XOpenDisplay

```

Process just hangs there with no game window opening until I terminate it with Ctrl-C. Should this be working or is it just something not implemented yet?

**Comment by fasterthanlime** [comment]
interesting! does your game not depend on libX11 at all?

**Comment by fractilegames** [comment]
The executable does not. It's just a launcher that dynamically loads a shared object with actual game code. The shared object depends on GLFW and Ogre3D which both depend on X11.

**Comment by fasterthanlime** [comment]
Fixed it! https://twitter.com/fasterthanlime/status/834695819802574848
